kgorde/WaterIsland_RiskPortal

- OLS_main.py
- OLS_regression_analysis.py
Updated Output in Json String Format
> Optimalpeer

- WicPortal_Django/settings.py
- portal/templates/error.html
- portal/views.py
Merge for custom error page for server
> Custom Error Page for Server

- templates/home.html
> Added Trading Widget

- WicPortal_Django/settings.py
- risk/views.py
- static/app-assets/js/core/ess_idea_database.js
Fixed error in populating fields in 'Edit ESS IDEA'
> Fixed error in populating fields in 'Edit ESS IDEA'

- OLS_main.py
- OLS_regression_analysis.py
- WicPortal_Django/settings.py
- nav_impact_utils.py
- realtime_pnl_impacts/templates/realtime_pnl_impacts.html
- realtime_pnl_impacts/views.py
- risk/models.py
- risk/tasks.py
- risk/templates/mna_idea_database.html
- risk/urls.py
- risk/views.py
- risk_reporting/models.py
- risk_reporting/tasks.py
- risk_reporting/templates/downside_fomulae.html
- risk_reporting/templates/risk_attributes.html
- risk_reporting/views.py
- static/app-assets/js/core/arb_risk_attributes.js
- static/app-assets/js/core/downside_formulae.js
- static/app-assets/js/core/exposures_snapshot.js
- static/app-assets/js/core/mna_idea_database.js
1. Automated Formulae_linked downsides
2. NAV Impacts updated and refreshes every 20 minutes
3. ESS IDEA emails now sent to risk, ted, curtis and kevin
> Multiple updates + new features

- WicPortal_Django/settings.py
- realtime_pnl_impacts/models.py
- realtime_pnl_impacts/templates/realtime_pnl_impacts.html
- realtime_pnl_impacts/views.py
- realtime_pnl_utilities.py
- risk/tasks.py
- risk_reporting/models.py
- risk_reporting/tasks.py
- risk_reporting/templates/downside_fomulae.html
- risk_reporting/urls.py
- risk_reporting/views.py
- static/app-assets/js/core/arb_risk_attributes.js
- static/app-assets/js/core/downside_formulae.js
- static/app-assets/js/core/realtime_pnl_impacts.js
- templates/base.html
1. You can now add a new deal in Formulae based downsides page
2. New deals with no downsides will be highlighted
3. User will be alerted if on Internet Explorer!
** Realtime PnL **
1. Realtime PnL shows all rows by default
2. Realtime PnL now shows Catalyst and Sleeve
3. Realtime PnL now can be filtered by Sleeve and Catalyst
** Extras **
RiskAutomation: File Send updated for new Deal Value column
RiskAutomation: Will now include logs in Daily Calc Report
> ** Multiple Updates **

- WicPortal_Django/settings.py
- risk/tasks.py
- risk_reporting/templates/downside_fomulae.html
- risk_reporting/views.py
- templates/portal_downsides.slack
> Fixed Formulae Downside calculation bug

- exposures/templates/exposures_snapshot.html
- portfolio_analytics/templates/deal_universe.html
- realtime_pnl_impacts/templates/realtime_pnl_impacts.html
- risk/templates/credit_database.html
- risk_reporting/templates/downside_fomulae.html
- risk_reporting/templates/merger_arb_nav_impacts.html
- risk_reporting/templates/risk_attributes.html
- risk_reporting/views.py
- static/app-assets/js/core/csrftoken.js
> Fixed CSRF Token issue

- risk_reporting/views.py
- templates/portal_downsides.slack
Ip address recorded in Slack Channel
> IP Address will be recorded in Formulae linked downsides update

- static/app-assets/js/core/arb_risk_attributes.js
> Bug fix in NAV Impacts

- WicPortal_Django/settings.py
- portal/tasks.py
> pool_recycle=3600

- .idea/WicPortal_Django.iml
- .idea/jsLibraryMappings.xml
- WicPortal_Django/settings.py
- risk_reporting/models.py
- risk_reporting/tasks.py
- risk_reporting/templates/risk_attributes.html
- risk_reporting/views.py
> ARB NAV Impacts Syncs on Celery

- risk_reporting/tasks.py
- risk_reporting/templates/risk_attributes.html
- static/app-assets/js/core/arb_risk_attributes.js
Last Synced on in Print View
Adjustment for FOXA - W US Price in NAV Impacts
> Last price adjustment for FOXA-W US

- risk_reporting/tasks.py
- static/app-assets/js/core/arb_risk_attributes.js
Fix for 'Waiting for table meta data lock'
> ORM used to delete instead of SQlalchemy

- risk_reporting/templates/downside_fomulae.html
Added None in Operation for formulae based downsides
> Added None in Operation for formulae based downsides

- risk_reporting/tasks.py
Line numbers will be shown in error: Slack channel
> Fixed IsExcluded parameter from downsides.

- WicPortal_Django/settings.py
- email_utilities.py
- risk/templates/show_ess_idea.html
- risk_reporting/models.py
- risk_reporting/tasks.py
- risk_reporting/views.py
- static/app-assets/js/core/arb_risk_attributes.js
- templates/portal_downsides.slack
1. Daily Email Backup of Formulae Linked Downsides(risk@wicfunds.com)
2. Slack view for portaldownsides channel improved
3. Risk Limits not updated through flat file anymore
4. Price for Underlying Sec in NAV Impacts
5. YTD PnL in NAV Impacts
6. More info. populated in Slack Channel for downside update
7. Risk Limit Report automatically sent 6.45 am
> New Features:

- risk_reporting/tasks.py
- risk_reporting/views.py
- static/app-assets/js/core/arb_risk_attributes.js
1. Fixed an Issue with Merger Arb NAV Impacts page (If downsides NULL)
2. NULL Downside Tradegroups will be shown on the report
3. Merger ARB Risk ATtributes closes old database connections in the view
> Bug Fixes:

- risk_reporting/tasks.py
- risk_reporting/views.py
> NAV Impacts Last Update fix

- risk_reporting/tasks.py
NAV Impacts Risk Limit reference from Formulae Page
> NAV Impacts Risk Limit reference from Formulae Page

- risk/models.py
- risk/tasks.py
- risk/templates/show_ess_idea.html
- risk/urls.py
- risk/views.py
- static/app-assets/js/core/show_ess_idea.js
ESS IDEA DB now shows Latest Regression Detailed Calculations
> ESS IDEA DB now shows Latest Regression Detailed Calculations

- ess_premium_analysis.py
- risk/views.py
- risk_reporting/templates/downside_fomulae.html
- risk_reporting/views.py
- static/app-assets/js/core/downside_formulae.js
- static/app-assets/js/core/show_ess_idea.js
> Bug Fix ESS IDEA DB

- risk/tasks.py
- risk/templates/show_ess_idea.html
- risk/views.py
- risk_reporting/templates/downside_fomulae.html
- risk_reporting/views.py
- static/app-assets/js/core/downside_formulae.js
- static/app-assets/js/core/show_ess_idea.js
ESS IDEA DB:
PT WIC, Upside and Downside will remain static (Not adjusted automatically)
Showed PT Wic and PT Regression on the frontend.
FORMULAE LINKED DOWNSIDES:
Add new deal parameters updated as per new request
Backend -
1. Automatically adds 2 positions if Acquirer position is held
** Other bug fixes **
> New Features and bug fixes

- risk_reporting/tasks.py
FOXA PUTS price not showing up
> NAV Impacts FOXA PUTS price not showing up

- WicPortal_Django/settings.py
- dbutils.py
- realtime_pnl_impacts/templates/realtime_pnl_impacts.html
- realtime_pnl_impacts/views.py
- risk/tasks.py
- risk_reporting/templates/downside_fomulae.html
- static/app-assets/js/core/arb_risk_attributes.js
- static/app-assets/js/core/downside_formulae.js
- static/app-assets/js/core/realtime_pnl_impacts.js
- static/app-assets/js/core/show_ess_idea.js
1. ESS IDEA 
- Order corrected
- Email reports looks better
2. Realtime P&L Impacts
- 2 tabs for Daily and YTD live pnl
- bug fixes
> New + Improvements

- risk_reporting/tasks.py
Changed Format of NAV Impacts Report
> Changed Format of NAV Impacts Report

- risk/tasks.py
> ESS IDEA DB Bug Fix for Premium Analysis
